#App
spring.application.name=expense-tracker

#DB
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=expense_tracker
spring.datasource.password=expense123

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration